<?php

namespace WTS_EAE\Modules\Charts\Skins;

use Elementor\Widget_Base;
use Elementor\Repeater;

class Skin_Bar_Chart extends Skin_Base {

    public function get_id() {
        return 'bar';
    }

    public function get_title() {
        return __( 'Bar', 'wts-eae' );
    }

    public function register_items_control( Widget_Base $widget ) {
        $this->parent = $widget;
    }

    public function register_style_controls() {
        //parent::register_style_controls(); // TODO: Change the autogenerated stub
       // $this->eae_charts_style_section();

    }

//    function additional_control(){
//        $repeater = new Repeater();
//
//        $repeater->add_control(
//            'bar_chart_background',
//            [
//                'label' => __('Bar Background', 'wts-eae'),
//                'type' => Controls_Manager::COLOR,
//            ]
//        );
//
//        $repeater->add_control(
//            'bar_border_width',
//            [
//                'label' => __('Border Width', 'wts-eae'),
//                'type' => Controls_Manager::NUMBER,
//                'min' => 1,
//                'max' => 10,
//            ]
//        );
//
//        $repeater->add_control(
//            'bar_chart_border_color',
//            [
//                'label' => __(' Bar Border Color', 'wts-eae'),
//                'type' => Controls_Manager::COLOR,
//            ]
//        );
//
//        $repeater->add_control(
//            'bar_thickness',
//            [
//                'label'     => __( 'Bar Width', 'wts-eae'),
//                'type'      => Controls_Manager::NUMBER,
//                'default'   => 60,
//                'min'       => 20,
//                'max'       => 100,
//            ]
//        );
//
//
//        $repeater->end_controls_tab();
//    }

	public function render() {
		$this->common_render();
	}
}